workflows:
  ios-app-preview:
    name: iOS App Preview
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build for App Preview
        script: |
          flutter build ios --debug --simulator

    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - build/ios/iphonesimulator/Runner.app.dSYM

    publishing:
      app_preview:
        enabled: true
