workflows:
  ios-app-store:
    name: iOS App Store Release
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.princealaa7.aplus"
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --platform IOS --create
      - name: Set up code signing
        script: |
          keychain add-certificates
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Run Flutter tests
        script: |
          flutter pub get
          flutter test
      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APPSTORE_PRIVATE_KEY
        key_id: $APPSTORE_KEY_ID
        issuer_id: $APPSTORE_ISSUER_ID
        submit_to_app_store: true
      email:
        recipients:
          - princealaa777@gmail.com  # ضع بريدك هنا
