workflows:
  ios-app-store:
    name: iOS App Store Release
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS IPA for App Store
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        issuer_id: $APPSTORE_ISSUER_ID
        key_id: $APPSTORE_KEY_ID
        private_key: $APPSTORE_PRIVATE_KEY
        submit_to_app_store: true
        submit_to_testflight: false
