workflows:
  ios-app-preview:
    name: iOS App Preview
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Build iOS Simulator App
        script: |
          flutter build ios --simulator --debug
          
    artifacts:
      - build/ios/iphonesimulator/Runner.app

    publishing:
      app_preview:
        enabled: true
