name: a9
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+12

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # إصدارات Firebase المحدثة والمتوافقة
  firebase_core: ^2.24.0
  firebase_auth: ^4.13.1
  firebase_database: ^10.3.4
  firebase_messaging: ^14.7.0
  firebase_app_check: ^0.2.2
  
  # مكتبات أخرى
  youtube_player_flutter: ^9.1.2
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^19.4.1
  http: ^1.1.0
  url_launcher: ^6.2.2
  image_picker: ^1.1.1
  uuid: ^4.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
