name: aplus
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+12

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_database: ^10.3.4
  youtube_player_flutter: ^9.1.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^19.5.0
  http: ^1.1.0
  firebase_messaging: ^14.7.4
  url_launcher: ^6.2.2
  firebase_auth: ^4.18.2
  image_picker: ^1.1.1
  uuid: ^4.2.1
  firebase_app_check: ^0.1.1+1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
