// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZm0XGY7T5jX-2Zn2hjJ_ZOb8sRBeLMYI',
    appId: '1:716867452897:android:a1def66043fffe78acdca0',
    messagingSenderId: '716867452897',
    projectId: 'essaybot-ed916',
    databaseURL: 'https://essaybot-ed916-default-rtdb.firebaseio.com',
    storageBucket: 'essaybot-ed916.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0XvNm0LTnn9Ehg4NpKda4kBOWSuxJwKY',
    appId: '1:716867452897:ios:aae20444ad0b5e18acdca0',
    messagingSenderId: '716867452897',
    projectId: 'essaybot-ed916',
    databaseURL: 'https://essaybot-ed916-default-rtdb.firebaseio.com',
    storageBucket: 'essaybot-ed916.firebasestorage.app',
    iosBundleId: 'com.princealaa7.aplus',  // تم التصحيح هنا
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_t8uw7F0qf-1hu9v6v7HmEKjPsnNPsk',
    appId: '1:716867452897:web:d33d2cd2cc19d208acdca0',
    messagingSenderId: '716867452897',
    projectId: 'essaybot-ed916',
    authDomain: 'essaybot-ed916.firebaseapp.com',
    databaseURL: 'https://essaybot-ed916-default-rtdb.firebaseio.com',
    storageBucket: 'essaybot-ed916.firebasestorage.app',
    measurementId: 'G-X5QY1176SG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0XvNm0LTnn9Ehg4NpKda4kBOWSuxJwKY',
    appId: '1:716867452897:ios:aae20444ad0b5e18acdca0',
    messagingSenderId: '716867452897',
    projectId: 'essaybot-ed916',
    databaseURL: 'https://essaybot-ed916-default-rtdb.firebaseio.com',
    storageBucket: 'essaybot-ed916.firebasestorage.app',
    iosBundleId: 'com.princealaa7.aplus',  // تم التصحيح هنا
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk_t8uw7F0qf-1hu9v6v7HmEKjPsnNPsk',
    appId: '1:716867452897:web:2568185de5de93e1acdca0',
    messagingSenderId: '716867452897',
    projectId: 'essaybot-ed916',
    authDomain: 'essaybot-ed916.firebaseapp.com',
    databaseURL: 'https://essaybot-ed916-default-rtdb.firebaseio.com',
    storageBucket: 'essaybot-ed916.firebasestorage.app',
    measurementId: 'G-6MYBTP0W7V',
  );
}
