name: Build & Upload iOS to TestFlight

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --release

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Upload IPA to TestFlight
        run: |
          fastlane pilot upload \
            --api_key_path ./AuthKey.p8 \
            --api_key_id ${{ secrets.APPSTORE_KEY_ID }} \
            --issuer_id ${{ secrets.APPSTORE_ISSUER_ID }} \
            --ipa "build/ios/ipa/*.ipa"
