name: Build iOS (Simulator, no signing)

on:
  workflow_dispatch:  # تشغيل يدوي

jobs:
  ios-sim-build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Show versions
        run: |
          flutter --version
          xcodebuild -version
          pod --version || true

      - name: Flutter pub get
        run: flutter pub get

      - name: CocoaPods (clean & install)
        run: |
          cd ios
          pod repo update
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS (Simulator, verbose)
        run: flutter build ios --debug --simulator -v

      - name: Collect .app
        run: |
          mkdir -p artifacts
          APP=$(find build/ios/iphonesimulator -maxdepth 3 -name "*.app" | head -n 1)
          if [ -z "$APP" ]; then
            echo "No .app found"; exit 1
          fi
          cd "$(dirname "$APP")"
          zip -r ../../../../artifacts/ios-simulator-app.zip "$(basename "$APP")"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-simulator-app
          path: artifacts/ios-simulator-app.zip
          if-no-files-found: error
